development:
  #adapter: sqlite3
  #database: db/development.sqlite3
  adapter: mysql
  database: treemap_development
  username: root
  password: 
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: treemap_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: posasdf
  database: treemap_development
  username: root
  password: 
  host: localhost
  encoding: utf8