#this is only used on local dev machines

development:
  adapter: mysql
  database: treemap_development
  username: root
  password: 
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: treemap_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: treemap_development
  username: root
  password: 
  host: localhost
  encoding: utf8